version: "3"

services:
  app:
    build: ./
    ports:
      - '8080:80'
    volumes:
      - ./:/app
    working_dir: /app
  db:
    image: postgres:11.2-alpine
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"