version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./storage/logs:/var/log/app
    ports:
      - '8080:8000'

  # db:
  #   image: postgres:11.2-alpine
  #   environment:
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: app
  #   ports:
  #     - "5432:5432"
